server:
  port: 8764
  servlet:
    context-path: /springCloudRibbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/springCloudServer/eureka/

spring:
  application:
    name: spring-cloud-ribbon

