server:
  port: 8773
  servlet:
    context-path: /springCloudServer1

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/springCloudServer/eureka/

spring:
  application:
    name: spring-cloud-server1
