server:
  port: 8763
  servlet:
    context-path: /springCloudProvider

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/springCloudServer/eureka/

spring:
  application:
    name: spring-cloud-provider

